spring:
  application:
    name: task_management

  profiles:
    active: dev

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true       # debug
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true                                      # Bật Flyway
    baseline-on-migrate: true                          # Tùy chọn: Đặt mốc cơ sở nếu schema đã tồn tại
    locations: classpath:/db/migration                 # VỊ TRÍ CỦA CÁC FILE SQL MIGRATION
    schemas: public                                    # Schema Flyway sẽ quản lý
    check-location: true
    validate-on-migrate: true


api:
  prefix: /api/v1